name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  try:
    uses: kungfu-systems/workflows/.github/workflows/.release-verify.yml@dev/v2/v2.0
    with:
      enable-linux: true
      enable-macos: false
      enable-windows: false
      build-container-enabled: false
      setup-python-enabled: false
      publish-versioning: false
      publish-aws-ci: false
      publish-aws-user: false
      action-bump-version-ref: dev/v4/v4.0
    secrets:
      AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
      AWS_USER_ACCESS_KEY_ID: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
      AWS_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
  
  verify:
    needs: try
    runs-on: ubuntu-24.04
    steps:
      - name: report
        run: echo verified
